### ISSUE TITLE
add support for incremental OTA builds

### ISSUE THREAD

**Issue by Stricted** [harryyoud/midnightsnack#13]
https://github.com/LineageOS/android_build/blob/cm-14.1/tools/releasetools/ota_from_target_files.py
https://forum.xda-developers.com/showthread.php?p=69760632#post69760632

**Comment by harryyoud** [comment]
No. This directly conflicts with #11

**Comment by Stricted** [comment]
im currentlty working on an idea to archive that without messing up the file system
https://github.com/Stricted/midnightsnack/tree/patch-7
https://github.com/harryyoud/midnightsnack/compare/master...Stricted:patch-7
